### ISSUE TITLE
Extended fuse warning.

### ISSUE THREAD

**Issue by ger-ator** [mysensors/ArduinoBoards#18]
Extended fuse should be 0xFE instead of 0x06. Avrdude complains about this when flashing bootloader on Sensebender Micro.

**Comment by sundberg84** [comment]
I can confirm this error - worked with 0xFE.

There is this note now from http://www.engbedded.com/fusecalc/

* Note that some numerical values refer to fuses containing undefined bits (set to '1' here). Depending on the target device these fuse bits will be read either as '0' or '1'. Verification errors will occur if the values are read back with undefined bits set to '0'. Everything is fine if the values read from the device are either the same as programmed, or the following values (undefined set to '0'): Extended: 0x06.

**Comment by tbowmo** [comment]
please note that the change should be made in the [ArduinoHwAVR](https://github.com/mysensors/ArduinoHwAVR) repository, and not here.. As this is a just a release / placeholder repository.

**Comment by ger-ator** [comment]
Sure. I'm opening a new issue there.
