### ISSUE TITLE
add instruction to README file where to add the setting

### ISSUE THREAD

**Issue by ikke-t** [mysensors/ArduinoBoards#5]
Please add this to README file to avoid further googling how to do it:

To add MySensors to Boards Manager list, go to IDE preferences, and at the bottom of the dialog add the following URL into "Additional boards managers URLs:" field and hit OK:
https://raw.githubusercontent.com/mysensors/ArduinoBoards/master/package_mysensors.org_index.json

**Comment by henrikekblad** [comment]
Hi Ikke, you can create a pull request to this repository by editing the README yourself.

Thanks
Henrik

**Comment by tbowmo** [comment]
I'm already preparing an pr with updated board defs for SAMD, where this issue is fixed

**Comment by ikke-t** [comment]
Ok, I wil not do it then, thanks @tbowmo.

**Comment by tbowmo** [comment]
This was fixed a long time ago... closing..
