### ISSUE TITLE
Error compiling when Arduino samd boards version > 1.6.8

### ISSUE THREAD

**Issue by kerios69780** [mysensors/ArduinoBoards#9]
Hello,

After downloading the defs of thesensebender gateway, I was not able to compile the gateway sketch.

I had to downgrade the samd boards from arduino to version 1.6.8
error was:
In file included from sketch/SensebenderGatewaySerial.ino.cpp:1:0:
.arduino15/packages/arduino/hardware/samd/1.6.11/cores/arduino/Arduino.h:48:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
exit status 1
Error compiling for board Sensebender Gateway.

**Comment by tbowmo** [comment]
We are aware of this, and @tekka007 have a made a fix in the code repository for ArduinoHwSAMD.. However, there is a problem with our build server, that I am trying to resolve, before we can have the fix in..
